name: Docker Image CI

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t test .
    - uses: actions/checkout@v3
    - name: Run the Docker image
      run: |
        docker run test
        CONTAINER_ID=$(docker ps -alq)
        ls
        sudo docker cp $CONTAINER_ID:/spisok.pdf .
        ls
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: ls -R
